# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.2.1']

    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: deployment
        env :
          SHINY_SECRET : ${{ secrets.SHINY_SECRET }}
          SHINY_TOKEN : ${{ secrets.SHINY_TOKEN }}
        run: |
          install.packages(c("rsconnect","devtools"))
          remotes::install_deps(dependencies = NA)
          var = as.list(Sys.getenv())
          rsconnect::setAccountInfo(name="sebastien",token=var$SHINY_TOKEN,secret=var$SHINY_SECRET)
          rsconnect::deployApp(launch.browser = FALSE,forceUpdate = TRUE)
        shell: Rscript {0}
